services:
  nginx:
    image: nginx:1.23.1-alpine
    ports:
      - "8088:80"
    volumes:
     - /docker/data/demo/nginx:/usr/share/nginx/html:ro
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.demo.rule=Host(`demo.hogwarts.zone`)
      - traefik.http.routers.demo.tls.certresolver=letsencrypt
      - traefik.http.routers.demo.middlewares=secHeaders@file
      - traefik.http.services.demo.loadbalancer.server.port=80
