services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  events_db:
    image: clickhouse/clickhouse-server:22.5-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      #- ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      #- ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.x>
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  app:
    image: plausible/analytics:v1
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - db
      - events_db
    ports:
      - "8888:8000"
    env_file:
      - /docker/secrets/plausible/plausible.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.plausible.rule=Host(`plausible.hogwarts.zone`)
      - traefik.http.routers.plausible.tls.certresolver=letsencrypt
      - traefik.http.routers.plausible.middlewares=secHeaders@file
      - traefik.http.services.plausible.loadbalancer.server.port=8000
volumes:
  db-data:
    name: db-data
  event-data:
    name: event-data
