name: 'Deploy to server'
on:
  push:
    branches:    
      - 'main'
jobs:
  deploy:
    name: 'Deploy to prod'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: 'Tailscale'
        id: tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }} # Ephemeral key
          version: 1.24.2
      - name: 'SSH'
        id: ssh
        if: steps.tailscale.outcome == 'success'
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOSTNAME }}
          SSH_USER: ${{ secrets.SSH_USER }}
      - name: Git pull
        id: git-pull
        if: steps.ssh.outcome == 'success'
        run: ssh staging 'cd /docker && git fetch && git checkout main && git pull'
      - name: Pull latest Docker images
        id: docker-pull
        if: steps.ssh.outcome == 'success'
        run: ssh staging 'for d in /docker/compose/enabled/*/ ; do (cd "$d" && docker compose pull); done'
      - name: Start enabled services
        id: docker-start
        if: steps.ssh.outcome == 'success'
        run: ssh staging 'for d in /docker/compose/enabled/*/ ; do (cd "$d" && docker compose up -d); done'
