name: 'Deploy to server'
on:
  push:
    branches:    
      - 'main'
jobs:
  deploy:
    name: 'Deploy to prod'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: 'Tailscale'
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }} # Ephemeral key
          version: 1.24.2
      - name: 'SSH'
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOSTNAME }}
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
      - name: Git pull
        run: ssh staging "cd ${{ secrets.COMPOSE_PATH }} && git fetch && git checkout main && git pull"
# Need to add Docker Compose up to activate containers.
